### ISSUE TITLE
Dropdown selectors for POI en Sheet don't fit next to each other on smaller screens

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#102]
On the iPhone 5/SE the sheet and POI selector in the menu bar don't fit next to each other and wrap around, messing up the layout. 

A possible fix could be to further scale the selectors. Another fix would be to create a different design (probably one with a larger menu bar where the selectors are places underneath each other) specifically for these small screens.

**Comment by Dacaspex** [comment]
On smaller screens, the dropdowns move underneath each other
![image](https://user-images.githubusercontent.com/5628526/57834122-df45e400-77bb-11e9-904f-d479656ab43e.png)

On bigger screens, when multiple sheets are selected, the dropdown grows vertically
![image](https://user-images.githubusercontent.com/5628526/57834170-fbe21c00-77bb-11e9-9b69-58f06c0f62ff.png)

**Comment by Erik9519** [comment]
See #190
