### ISSUE TITLE
Styling of help page not working on certain screen sizes

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#105]
- Image not centered when the screen is small
- Text overlaps the keys when the screen is small
- Layout on mobile can be improved

![image](https://user-images.githubusercontent.com/5628526/57833849-49aa5480-77bb-11e9-8881-2a2abde99e90.png)

**Comment by Astrejoe** [comment]
>     * Image not centered when the screen is small
> 
>     * Text overlaps the keys when the screen is small
> 
>     * Layout on mobile can be improved
> 
> 
> ![image](https://user-images.githubusercontent.com/5628526/57833849-49aa5480-77bb-11e9-8881-2a2abde99e90.png)

What do you mean with _images not centered_? How should they be centered?
