### ISSUE TITLE
Tooltips for animation toolbar add scrollbar

### ISSUE THREAD

**Issue by Chessnl** [Dacaspex/Exhibit#108]
When a tooltip shows up in the animation toolbar, the tooltip flows outside the canvas, resulting in a scrollbar that is not needed.

![Untitled-2](https://user-images.githubusercontent.com/34745596/57843504-ad8a4880-77ce-11e9-9d93-0d056230f9f5.jpg)

![Untitled-1](https://user-images.githubusercontent.com/34745596/57843500-ac591b80-77ce-11e9-9b6d-8ddea80c9f9d.jpg)

**Comment by Dacaspex** [comment]
The toolbar is currently in progress. We should re-assess this issue once this has been done #78

**Comment by Dacaspex** [comment]
Too old and not relevant anymore
