### ISSUE TITLE
When clicking toggle buttons on desktop, highlighting only leaves when clicking elsewhere

### ISSUE THREAD

**Issue by Chessnl** [Dacaspex/Exhibit#109]
Clicking a toggle button on desktop gives a highlight, however, it only disappears when clicked elsewhere and not on the mouse-leaving this button.

![Untitled-3](https://user-images.githubusercontent.com/34745596/57844019-88e2a080-77cf-11e9-9ab2-7e091296b958.jpg)

**Comment by Dacaspex** [comment]
That's a feature, not a bug :P The component is then focused, this is how a browser works.
