### ISSUE TITLE
Icons for navigation purposes have inconsistent sizing across views

### ISSUE THREAD

**Issue by Chessnl** [Dacaspex/Exhibit#111]
The buttons (arrow and plus sign) on the import screen are not of equal size as the buttons (arrow and triple v-dots) on the menu panel for phone view and the buttons (arrow and help) on the menu panel for desktop view.

A suggestion is to reduce button size on the import screen.

![Untitled-4](https://user-images.githubusercontent.com/34745596/57844431-52595580-77d0-11e9-8225-22c8b087e92b.jpg)

![Untitled-5](https://user-images.githubusercontent.com/34745596/57844435-538a8280-77d0-11e9-9946-de42b99acbf1.jpg)

**Comment by Dacaspex** [comment]
Perhaps we could use a different icon set if the icons cannot be made thinner

**Comment by cwognum** [comment]
I don't think Jeroen meant this as an issue concerning the thickness of the icon, but rather the scaling of a icon. From the top of my head, I think we used 2x scaling for the import buttons, but not for the menu buttons.

So `<fa name="cog" size="2x"></fa>` vs. `<fa name="cog"></fa>`
