### ISSUE TITLE
Throw parsing error if there are no timing entries for a SheetTiming

### ISSUE THREAD

**Issue by Extremelyd1** [Dacaspex/Exhibit#139]
The parser should throw an error when trying to make a `SheetTiming` instance without any timing entries associated with it. Although this should never happen, we have to assume it in further code, so if not checked it cannot be assumed with certainty.

**Comment by nolmoonen** [comment]
Non-issue: `SheetTiming` throws `IllegalArgumentError` in constructor when initializing with empty `TimingEntry` array.
