### ISSUE TITLE
Extend SheetStateConstructor with POI information

### ISSUE THREAD

**Issue by marijnvanderhorst** [Dacaspex/Exhibit#140]
For every sheet, for every selected POI we need the following extra data:
* Absolute time when sheet was at POI
* Relative time when sheet was at POI
* Time since sheet was at POI (negative if not yet visited)
* Distance relative to POI
* Velocity when sheet was at POI
* Acceleration when sheet was at POI

**Comment by nolmoonen** [comment]
Firstly, I will add for each POI an array of its positions on the route.

**Comment by nolmoonen** [comment]
See #181 for route positions.
