### ISSUE TITLE
Configuration/Table/Graph panel desktop view large view

### ISSUE THREAD

**Issue by Chessnl** [Dacaspex/Exhibit#141]
When working in mobile, the user has the possibility to enlarge the table/graph to cover the full screen (removes viewport). However, on desktop, there is no such functionality. Seeing that the tables themselves can become rather large, it would be quite useful to also be able to remove the viewport on desktop.

One possible solution would be to have a continuous range of heights by dragging those panels upwards. Another solution would be having 2 discrete ranges similar as on the phone.

**Comment by Dacaspex** [comment]
This is not a requirement and therefore I would not add this feature.
