### ISSUE TITLE
[20] Introduction

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#16]
Estimate: 6

**Comment by Vogeltak** [comment]
- [x] 1.1 Purpose
- [x] 1.2 Scope
- [x] 1.3-1.4 List of definitions and abbreviations
- [x] 1.5 List of references
- [x] 1.6 Overview

Fixed a few language errors. _Purpose_ and _scope_ are directly taken from the URD and amended to fit the ADD. By nature of the introduction to all our documentation, this is acceptable.

List of definitions and abbreviations is already filled with the entries relevant to this document. The same holds for the list of references.

Overview is okay.

Ready for first draft version. Has not been read by supervisor nor product owner yet.
