### ISSUE TITLE
Fix bottom drawer arrow floating too high on mobile

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#205]
On mobile, the bottom right arrow floats too high. When fully minimized, the arrow actually floats at the correct position but the grey bar does not appear so the arrow floats. When the bottom area is expanded once, the arrows float too high. 
It works fine in developer tools. Only when displaying on an actual phone did this bug appear.

**Comment by SquarePlayn** [comment]
![Screenshot_20190522-162125](https://user-images.githubusercontent.com/7192111/58182829-9a83e680-7cae-11e9-92c5-4db7ba4f1e1b.jpg)
![Screenshot_20190522-162120](https://user-images.githubusercontent.com/7192111/58182830-9b1c7d00-7cae-11e9-9bab-517fcc52f579.jpg)

**Comment by cwognum** [comment]
I tested a bit on phone today and did not recall encountering this bug... :(
