### ISSUE TITLE
[19] Introduction

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#22]
Estimate: 10

**Comment by Vogeltak** [comment]
Sections on _purpose_ and _scope_ are taken from the URD and amended to reflect the SRD perspective.

The list of definitions and abbreviations are initialized with the entries from the URD, and can be changed over time to reflect what is found to be necessary in the SRD.

The overview is correct for the sections required by the SRD.

- [x] 1.1 Purpose
- [x] 1.2 Scope
- [x] 1.3 List of definitions and abbreviations
- [x] 1.4 List of references
- [x] 1.5 Overview

Ready for the first draft version. Has not been read by supervisor nor product owner yet.
