### ISSUE TITLE
Change the implementation of FileReader to something that can work with fake async

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#222]
The current implementation of the parse service uses the `FileReader`. Unfortunately, that implementation does not work with fake async, which is required in order to properly test the parse function. 

Therefore, we need an implementation of a file reader that works with fake async / macrotasks / promises.

**Comment by Dacaspex** [comment]
Related Github issue https://github.com/angular/zone.js/issues/1120

**Comment by Dacaspex** [comment]
> @Dacaspex one workaround: use new Response(file).arrayBuffer() instead of FileReader, with promise support

**Comment by Dacaspex** [comment]
The `Response().then()` implementation does not seem to work as well, as the promises are not properly flushed in the `fakeasync` environment

**Comment by cwognum** [comment]
@Dacaspex This is fixed, right? Can it be closed?
