### ISSUE TITLE
[19] Description

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#23]
Estimate: 24

**Comment by Vogeltak** [comment]
What is still left to do before it can move to verification:
- [ ] finish rewriting _2.1 Relation to current projects_
- [ ] rewrite _2.5 Relation to other systems_

**Comment by Vogeltak** [comment]
Verified and improved several small grammatical mistakes.

Ready for the first draft version. Has not been read by supervisor nor product owner yet.
