### ISSUE TITLE
[SRD] functional requirements: 3.1.11 Graph

### ISSUE THREAD

**Issue by ArtixOfVenion** [Dacaspex/Exhibit#230]

**Comment by nolmoonen** [comment]
A few comments:
* `ChartOptions`, `Color`, `ChartType`, `ScatterChartDataSets`, `ResizedEvent` are all not standard objects. Can you explain these in more detail (preferably above the `Attributes` section)? 
* Also, all types, except void, are written with a capital letter. I changed this already.
* Please end all (text) sentences with a dot (.) I changed this also already.

**Comment by ArtixOfVenion** [comment]
I adjusted the graph section according to your comments. I'm not sure if my explanation of the data types were elaborate enough/correct. Perhaps you could review if this is what you had in mind?

**Comment by nolmoonen** [comment]
Looks good, but please add a reference (with footnote) to the library mentioned.

**Comment by ArtixOfVenion** [comment]
Added a footnote as requested.

**Comment by Vogeltak** [comment]
Okay, so I am aware of my previous statements on this section and my encouragement of the direction it was heading. But just now I became aware of the fact that this is _very_ implementation specific and thus should not be in the SRD.

I would suggest to remove all these specific attributes and to only include a generic `options` object or something similar. This section should also be extended with the changes made by @marijnvanderhorst and @Vogeltak with respect to the data connection.
