### ISSUE TITLE
[3] Planning how to render sheets from 1/2 timing files

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#241]
Estimate: 5h

**Comment by Dacaspex** [comment]
How we are going to render the sheets:
- Each sheet from timing file x has the same colour
- Sheets from timing file x and timing file y have different colours
- Colours are somewhat transparent
    - This ensures that we can see sheets from timing file x and timing file y when they overlap
- Each sheet has a thickness
    - This ensures that we can see the paper in orthographic view, from the side

**Optional**
- Sheet s from timing file x and timing file y can be connected by a coloured line
    - This is an option that can be enabled/disabled from the settings menu

**Comment by cwognum** [comment]
![Untitled-1](https://user-images.githubusercontent.com/28000055/58409875-52c7db00-8071-11e9-8709-ff9197309072.png)
