### ISSUE TITLE
SUM basic layout

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#261]
Make a start on the Software User Manual

**Comment by Vogeltak** [comment]
I have rewritten sections:
- 1.1 Intended readership
- 1.3 Purpose
- 1.4 How to use this document
- 1.7 Problem reporting

Request for changes
- Chapter 2 should be rewritten to accommodate the intention as set out in the document info file provided by the course.
- Chapter 3 Tutorials. Write template similar in style to ATP with commands.
