### ISSUE TITLE
ATP basic layout

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#262]
Make a start on the basic layout for the Acceptance Testing Plan

**Comment by cwognum** [comment]
https://www.overleaf.com/project/5cee6d9751f0173a7a171cc6

**Comment by Dacaspex** [comment]
> Restricted, sorry you don't have permission to load this page.

**Comment by cwognum** [comment]
Oops. Did not notice your comment. Rookie mistake. Here is the updated link; 
https://www.overleaf.com/2593548946thkbszvdcwqx

**Comment by nolmoonen** [comment]
**I removed the link to the document. Keep in mind this is a public space!**

**Comment by nolmoonen** [comment]
1. Logo on front page is not aligned properly.
1. Missing citations in abstract. Also, I think the citation for the SRD can be removed. How do you intend to link to this?
1. Chapter `Test case specifications` has not subsections, like chapters 4 and 5 have.
1. Traceability Matrix and appendix are not in document describing ATP, where are these described?

If these points are addressed, this task is done in my opinion.
