### ISSUE TITLE
POI selector resizes when it has a selection.

### ISSUE THREAD

**Issue by TijnBertens** [Dacaspex/Exhibit#263]
When the POI selector contains a selected element, it will resize/un-align itself slightly. See the following screenshots.

![image](https://user-images.githubusercontent.com/7274733/58466168-6b9bc380-8139-11e9-9f19-5032a8a7293e.png)

![image](https://user-images.githubusercontent.com/7274733/58466187-722a3b00-8139-11e9-9dc9-eb3b807e74c3.png)

**Comment by cwognum** [comment]
Looked into this for a bit a couple of days ago. Has to do with a margin or padding that is added to the component that displays the selected item if I recall correctly

**Comment by SquarePlayn** [comment]
This also applies to the dropdown of the table
