### ISSUE TITLE
UTP basic layout

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#287]
Has the same layout as the ATP and thus overlaps with #262

**Comment by cwognum** [comment]
https://www.overleaf.com/project/5ceea33d51f0173a7a173a96

**Comment by cwognum** [comment]
Enabled link sharing; 
https://www.overleaf.com/2995936153fkgdxtmxjksp

**Comment by cwognum** [comment]
**Very important:**
Image on the title page is a very deliberate choice. First of all, we use this picture in the UI and it fits the style (paint and such), so that is great. But! See all those little squares on it? Does that not remind you of something? *wink* *wink* code coverage *wink* *wink*

**Comment by nolmoonen** [comment]
**I removed the link to the document! Keep in mind this is a public space!**

**Comment by nolmoonen** [comment]
- Missing citations in abstract. Also, I think the citation for the SRD can be removed. How do you intend to link to this?
- Chapter 5 is called `Test coverage`, while this is not in the document describing the UTP.
- Chapter `Test case specifications` has not subsections, like chapters 4 and 6 have. Alternatively, leave out the test items (sections), but add subsections.

If these points are addressed, this task is done in my opinion.
