### ISSUE TITLE
Keyboard shrinks the UI

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#290]
Hard to make a decent screenshot as the keyboard would disappear as soon as I tried to. But when you click the sheet selector on mobile (and probably other selectors as well), the keyboard pops up and makes the screen so small that it messes up the UI. 
![image](https://user-images.githubusercontent.com/28000055/58591192-02659e80-8266-11e9-9cdd-0a1f72874fcd.png)

**Comment by Astrejoe** [comment]
The easiest way to fix this is to add `[searchable]="false"` to the `ng-select` class. However, this removes the ability to search for specific sheets by typing the name. We could also only only disable this on mobile. But if we still want to include the search functionality on mobile, then I predict that this won't be an easy fix.
