### ISSUE TITLE
Fix dropdown having different placeholder text when nothing is selected

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#295]
For the table row & column selector dropdowns, we use the field for generation of the items to instead just display some "configure _columns_" text. However, when there are no items selected, this part is not run (since there originally would not be any items to display), and the normal placeholder text is displayed. This text, however, is not made bold the same way so it looks slightly different.

https://github.com/Dacaspex/Exhibit/blob/6ca12193faef2f1f324ee775b4bd748f869cde64/src/app/table/table.component.html#L17-L23

**Comment by cwognum** [comment]
@SquarePlayn @Dacaspex This issue was mentioned in a merged PR, but I cannot find this reference. I also don't fully understand the issue.

**Comment by SquarePlayn** [comment]
> @SquarePlayn @Dacaspex This issue was mentioned in a merged PR, but I cannot find this reference. I also don't fully understand the issue.
Explained in person. 
Basically, with at least one item selected, one type of text is used:
![With items selected](https://i.imgur.com/NMOnbeJ.png)
But when none are selected, it uses the ng-select placeholder text, which is a lot lighter.
![Without items selected](https://i.imgur.com/dmQqBVF.png)
