### ISSUE TITLE
[4] Desktop

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#30]
Estimate: 5

**Comment by Vogeltak** [comment]
For the bottom footer panel containing the tabs for the different panels, I would suggest we use the checkbox buttons from ngBootstrap: https://ng-bootstrap.github.io/#/components/buttons/examples#checkbox.

This can directly influence model variables, indicating the status of the different panels; either shown or hidden.

**Comment by Extremelyd1** [comment]
This has been placed in "Verify", however I don't think this is finished, nor is there a PR open for it. I assume this was a mistake?

**Comment by Dacaspex** [comment]
Issues have been split up into: #74 #75 #76 #77 #78 #79
