### ISSUE TITLE
[SheetStateEngine] POIMetrics are not being calculated when sheet is not currently in the system

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#320]
When a sheet is not in the system (it is _dead_ / not _alive_), there are no POIMetrics calculated. This means that you cannot, for example, get the speedAtPOI for a sheet that is not in the system currently. 
This is required for example in the table, where rows for selected sheets are displayed regardless of them being in the system or not, to more easily see data from the selected sheets.

**Comment by nolmoonen** [comment]
#382 fixes the bug, another issue will be created to provide functionality.
