### ISSUE TITLE
[Table] Set fixed / constant width of tale cells so they do not keep growing/shrinking

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#324]
Partially related to #322

**Comment by cwognum** [comment]
https://stackoverflow.com/questions/26809157/table-wider-than-bootstrap-column-container

**Comment by cwognum** [comment]
Adding an `overflow-x: scroll` works, but adds ugly scrollbars

![image](https://user-images.githubusercontent.com/28000055/59044381-554edf80-887e-11e9-8bb8-db5fa61252f7.png)

**Comment by SquarePlayn** [comment]
@cwognum @Astrejoe This issue was meant for setting constant width on the table columns/cells, not on the whole table itself.
