### ISSUE TITLE
[SRD] Table

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#325]

**Comment by SquarePlayn** [comment]
Regarded sections:
- 3.1.38 Table
- 3.1.2 Column
- 3.1.3. ColumnService
- 3.1.25 Row
- 3.1.26 RowService
- 3.1.6 Entry
(The subsection numbers can change when others add subsections)

**Comment by Vogeltak** [comment]
Take care to use italics for component names (e.g. _SheetTimingState_, or _POI_). You should also end every sentence **and phrase** with a dot. I have corrected all these things throughout all pieces.

Very good contribution nonetheless!
