### ISSUE TITLE
[1] Desktop

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#33]
Estimate: 2

**Comment by nolmoonen** [comment]
Most recent version of file is located at "09 Mockup/mockup-desktop.xd"

**Comment by nolmoonen** [comment]
[Link to inspect current version as of writing this comment.](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off) Scaling in this preview does not work as intended however: aspect ratio is maintained, while it is not indented to be.

**Comment by Vogeltak** [comment]
I would suggest the following:
- remove the space between the X and multiplier in the animation speed component.
- use the dark Océ brand image; see [Océ brand page](https://brand.oce.com/portfolio-item/logo/).

**Comment by nolmoonen** [comment]
[Updated version](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off), updated drive file as well.

**Comment by nolmoonen** [comment]
[Updated again](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off) per request of @Vogeltak , updated drive as well.

**Comment by nolmoonen** [comment]
[Updated again](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off) per request of @Vogeltak and @Dacaspex  , updated drive as well.

**Comment by Vogeltak** [comment]
Accepted as non-conclusive design mock up.
★★★★☆

**Comment by nolmoonen** [comment]
[Updated again](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off), updated drive as well. In this version:
* Bottom panels can be hidden by clicking the button in the right bottom corner. This is for MPS compatibility.
* Changed color of sheet selector dropdown menu.

**Comment by nolmoonen** [comment]
[This link wil update automatically.](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen&hints=off) Main changes in this version:
* Added scrollbars to panels.
* Updated graph image.
* All "sheet" variables are changed to "sheet 3".
* Changed some icons for buttons to make more intuitive.
* Moved speed up/down controls to the right.
* Highlight selected entry in table.

**Comment by nolmoonen** [comment]
Incorporated customer feedback. 
Main changes in this version:
* Added point of interest selector on top of screen
* All panels are individually collapsible. Opened panels will scale the width equally.
* Removed "hide all panels" button, since all panels can now be hidden individually.

**Comment by nolmoonen** [comment]
* Re-added total simulation time.

**Comment by nolmoonen** [comment]
* Hiding of table column (in the screen where all panels except the table are hidden).

**Comment by nolmoonen** [comment]
[Updated link with hints.](https://xd.adobe.com/view/bb2ad8d6-8347-42ad-7a66-63f652bed604-cd1b/?fullscreen)
