### ISSUE TITLE
Add debug mode for testing purposes

### ISSUE THREAD

**Issue by Extremelyd1** [Dacaspex/Exhibit#331]
For instance add a boolean to display the focus point in the viewport scene.

**Comment by Extremelyd1** [comment]
Also add information about distances, since we have requirements stating that something should move at most 500 meters.

**Comment by Extremelyd1** [comment]
Maybe have a circle of radius 500m to show the bounds of the camera movement

**Comment by cwognum** [comment]
We decided not to do this. The client did not ask for a visual indicator in the URD and we do not want such a debug mode in our production code.
