### ISSUE TITLE
[1] MPS

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#35]
Estimate: 5

**Comment by nolmoonen** [comment]
See #33 .

**Comment by ArtixOfVenion** [comment]
- Are the scene and model configuration windows scrollable? If so perhaps add a scrollbar to indicate this.
- The same as previous comment for the statistics table

**Comment by nolmoonen** [comment]
> * Are the scene and model configuration windows scrollable? If so perhaps add a scrollbar to indicate this.
> * The same as previous comment for the statistics table

This has been addressed in the latest version of #33 .

**Comment by Extremelyd1** [comment]
Since #33 has been moved to "Done" and closed, I assume this is done as well.
