### ISSUE TITLE
[UTP] Layout / structure chapter 3

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#352]

**Comment by Vogeltak** [comment]
So currently for a specific test case you use the following structure:
- Test case identifier
- Test case description
- Test subject
- Pre-condition
- Input
- Post-condition

However, the _Document Info_ prescribes the structure given below:
- Test case identifier
- Test items
- Input specifications
- Output specification
- Environmental needs

How do you see these mapping to your own structure?

Maybe we could merge them like follows:
- Test case identifier
- Test case description
- Test subject
- Input specifications
- Output specifications _(basically your post-condition currently)_
- Environmental needs _(basically your pre-condition currently)_

---

Furthermore, make sure to always end sentences **and phrases** with a dot.

---

Finally, the list of components has been updated while this has not been reflected in your current outline yet. See the _SRD responsibility matrix_ for a complete overview.
