### ISSUE TITLE
[URD] Stuff to update

### ISSUE THREAD

**Issue by Extremelyd1** [Dacaspex/Exhibit#354]
URD 1.1.7 change bounds (removed entirely, still needs to be discussed)
URD 1.1.8 change lower bound (changed)

**Comment by Extremelyd1** [comment]
URD 1.1.15, 1.1.16 VRAM metric is incorrect
URD 1.1.15, 1.1.16, 1.1.17 the ordering of display is wrong

**Comment by cwognum** [comment]
URD 1.4.5 Pause button is not shown anymore on initialization
URD 1.4.10 Reset button is not in the application anymore

**Comment by Extremelyd1** [comment]
URD 1.8.1 "over the last 100 seconds" is not relevant anymore

**Comment by cwognum** [comment]
URD 1.4.2 Not relevant anymore. Should be `minTime`

**Comment by cwognum** [comment]
We implemented components in the application that are not in the URD (like the slider in the animation toolbar). If you think of it, it is a bit weird that we did this. Should we change the URD to reflect these changes?

**Comment by Extremelyd1** [comment]
URD 1.9.1 "visual" should be "visible"

**Comment by Extremelyd1** [comment]
URD 1.9.3 this should be removed

**Comment by cwognum** [comment]
URD 1.10.3 and URD 1.10.4  Contradicting priorities

**Comment by Extremelyd1** [comment]
URD 1.9.8 there should also be a requirement with distance to next and the distance to prev. POI

**Comment by cwognum** [comment]
URD 1.2.7 "If _a light_" should be "If _a directional light_"

**Comment by cwognum** [comment]
URD 1.3.9 and URD 1.3.10 Contradicting priorities

**Comment by cwognum** [comment]
URD 1.3.3 to URD 1.3.7 Labels are not correct

**Comment by cwognum** [comment]
URD 1.3.3 "X-Grid"
URD 1.3.4 "Y-Grid"

Why X and Y? Should it not be horizontal / vertical

**Comment by cwognum** [comment]
URD 1.5.2 Not true at the moment

**Comment by Extremelyd1** [comment]
URD 1.7.1-1.7.10 Needs to be looked at, 0.5 seconds in some of these is not realistic

**Comment by cwognum** [comment]
We do not have any requirements for the Model tab in the  Configuration panel

**Comment by Extremelyd1** [comment]
URD 1.5.5 is not relevant anymore

**Comment by cwognum** [comment]
URD 1.1.32 has an O priority, but is the essence of the entire application.

**Comment by Extremelyd1** [comment]
URD has been updated with the above comments

**Comment by Extremelyd1** [comment]
The client requested to change the priorities of requirements related to x-error to be "Attractive":
1.1.23, 1.3.8, 1.6.18, 1.9.10
