### ISSUE TITLE
Panels move underneath each other

### ISSUE THREAD

**Issue by cwognum** [Dacaspex/Exhibit#364]
![image](https://user-images.githubusercontent.com/28000055/58960019-8f4cb280-87a6-11e9-989b-6d6ed75f433b.png)

**Comment by Astrejoe** [comment]
I can't seem to recreate this problem. Can you specify when this problem occurred?

**Comment by Dacaspex** [comment]
@cwognum Where you able to reproduce the problem?

**Comment by cwognum** [comment]
I think this was fixed when the table got a fixed width. I'll close it for now
