### ISSUE TITLE
Graph crashes when it is not opened before importing data

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#384]
Steps to reproduce:
1. Open Exhibit
2. Do not open the graph panel
3. Import files
4. Try opening the graph panel
    - Observe that the application crashes

1. Open Exhibit
2. Open the graph panel
3. Import files
4. Open the graph panel
    - Observe that the application does not crash

**Comment by Dacaspex** [comment]
@marijnvanderhorst you mentioned this during standup right?

**Comment by marijnvanderhorst** [comment]
@Dacaspex Are you sure this happens with the graph, rather than the table?
I did not encounter any problems with the graph so far, but I did with the table.

**Comment by marijnvanderhorst** [comment]
Unable to reproduce
