### ISSUE TITLE
Hook up SheetStateEngine to the dispatch update loop

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#394]
Example of how one could make it _work_ (to get you started):
Inject sheetStateEngine into the dispatch component and add to the update() function the line this.sheetStateEngine.updateSheetService();.
Then in the sheetStateEngine's updateSheetService() function, change the content of the if statement to just return (so don't throw an error).

However, the current architecture design would be to have the sheetStateEngine subscribe to an update event of the dispatcher.

**Comment by nolmoonen** [comment]
Addressed in #378 .
