### ISSUE TITLE
Invert dependency of time and dispatch

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#395]
Currently, the dispatch calls the time to update. In our design, however, the dependency should be reversed, where the time subscribes to an update event of the dispatcher. 
An example of this can already be seen in the Viewport, which does the subscribing.

**Comment by Dacaspex** [comment]
I thought we already discussed this and we wanted to explicitly do this, right? We should discuss tomorrow

**Comment by SquarePlayn** [comment]
Noting down for now: While I instead (in class diagram setting) was told the dependency would be inverted to use the subscription, I think that'd give problems with the time not updating before the viewport updates and likewise for viewport & sheetStateEngine. Unless separate events are used of course.
But yes let's discuss tomorrow.

**Comment by SquarePlayn** [comment]
Checked with Marijn and Casper. Dispatch will call (/depend on) time and SheetStateEngine and provide a render event that the viewport can depend on by subscribing to it.
Added this to the class diagram (which is printed. Check the dependencies of dispatch there).

**Comment by Dacaspex** [comment]
This has been resolved now?

**Comment by SquarePlayn** [comment]
Yes
