### ISSUE TITLE
Fill help page with content

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#400]

**Comment by Astrejoe** [comment]
The first thing we need to do is decide on all the keyboard shortcuts and gestures. I heard from Erik that we use the following commands:
desktop:
A, W, S, D for moving the model around on desktop.
5 for switching between orthographic and and perspective view

mobile:
swiping in viewport for moving camera

What other gestures/ shortcuts are we using?

On top of that I am going to add guides on how to use the different components (import, table, graph, settings.) Next week, I will probably ask some people who made the various components for help.
