### ISSUE TITLE
Sheets suddently disappearing

### ISSUE THREAD

**Issue by Erik9519** [Dacaspex/Exhibit#420]
Timing Files used together:
real_TimingExport_SCS931000724_2335
expected_TimingExport_SCS931000724_2335

At timestamp 03:03:250 the blue sheet 32 suddenly disappears. 
This happens multiple times with different sheets.
When the timestamp reaches the end sheet the orange sheet 34 is still in the printer.

**Comment by cwognum** [comment]
@TijnBertens Is this fixed?
