### ISSUE TITLE
Update help page

### ISSUE THREAD

**Issue by Astrejoe** [Dacaspex/Exhibit#432]
Update help page according to newest changes:
-Screenshots should be updates (new colors table, new buttons import screen)
-Pressing P for debug mode should be listed in the list of controls
-It should explain how to turn the website to an app on mobile chrome. (For fixing the issue on mobile chrome)

**Comment by Chessnl** [comment]
- Debug mode is no longer relevant

**Comment by Chessnl** [comment]
Un-assigning this from myself, as I:
- don't have the template in which the images are made
- don't really know how to turn the website to an app on mobile

As well, this should probably be picked up at the end of the week.
