### ISSUE TITLE
Table throws error when selecting POI.

### ISSUE THREAD

**Issue by TijnBertens** [Dacaspex/Exhibit#478]
When selecting a POI whilst the table is open, an error gets thrown. The hypothesis is that this is because the selected POIs change in between updates of the `SheetStateEngine`, whilst the table expects changes immediately.

![image](https://user-images.githubusercontent.com/7274733/59683874-3aaf2b80-91d9-11e9-92bb-0e0b60b3e130.png)

**Comment by cwognum** [comment]
> The table is perfect
