### ISSUE TITLE
Display a message to users that have JavaScript disabled

### ISSUE THREAD

**Issue by SquarePlayn** [Dacaspex/Exhibit#486]
Some people have JavaScript disabled. For them currently when they load the page, nothing is shown at all, only a blank page.
It would help for them to know they should turn on JavaScript if they saw a simple message stating that the website depends on JavaScript

**Comment by Dacaspex** [comment]
Who, these days, has JS disabled?

**Comment by SquarePlayn** [comment]
No clue how accurate this source is, but apparently around 2%
https://www.searchenginepeople.com/blog/stats-no-javascript.html

But I added this issue more for completeness, maybe it's very easy then it's nice to add
