### ISSUE TITLE
[23] Finish mockups

### ISSUE THREAD

**Issue by TijnBertens** [Dacaspex/Exhibit#63]

**Comment by cwognum** [comment]
**Desktop link**
https://xd.adobe.com/view/e5626e7c-08ff-4207-410b-5319511e608a-9353/

**Mobile link**
https://xd.adobe.com/view/562aeb16-ab2b-4478-75b5-e65572b06b51-201b/

With these new mockups, the interactions on both desktop and mobile are very similar. 
 
I am not entirely happy yet with the looks on Desktop, but I think that if the table and graph are a bit better styled, this already makes a big difference.
